### PR TITLE
remove page delimiter, start new page by header 1(one sharp)

### PR DESCRIPTION
**Pull request by liubin**
Now new page start by '---', I think we can use only "# " to start a new page.

### CODE REVIEW

**Comment by k0kubun** [comment]
Thank you for writing a pull request. :)
That's true. We can remove `---` from the required format with the current design.

But I have a reason to keep this specification. While current implementation is too simple, my personal goal of this product is to make the replacement of [Deckset](http://www.decksetapp.com/). It paginates slides with `---` and it accepts multiple `#`s in one slide. So I want to keep the compatibility of md2key's default behavior.

Because the goal is far from here, your proposal seems quite reasonable for now. So I have no objection to adding such a format. How do you think about following usage?

```bash
# like deckset
$ md2key slide.md

# a simple mode you provided, without `---`
$ md2key -s slide.md
$ md2key --simple slide.md
```

And I think it'd be more convenient to have `~/.md2key` with YAML, which can set a simple mode as default.

**Comment by k0kubun** [comment]
OK, I'll change the implementation to just ignore `---`. It'll be backward-compatible.

**Comment by k0kubun** [comment]
I changed so in 9c966c67143972f196f3240993a3e94aa471a8f0 and released as v0.1.2. :gem: 
Thank you for your contribution.

**Comment by liubin** [comment]
Thanks

I have never used deckset, but I think if md2key can add these two feature will OK fro me:

- Add Image (``)
- Even more show code syntax highlight

Thanks.

**Comment by k0kubun** [comment]
> Add Image (``)
> Even more show code syntax highlight

Yes, they are strongly desired features for me too. Thank you for your feedback :)

**Pull request merged**
