### PR TITLE
Use AppleScript

### PR DESCRIPTION
**Pull request by bogem**
Move AppleScript logic to separate AppleScript files:
* Reduce code (convenient to read Keynote class now)
* Improve performance (remove operations with creating new applescript files; remove code which create huge strings with AppleScript code)

### CODE REVIEW

**Comment by k0kubun** [comment]
Thank you for your contribution! :+1:

**Comment by bogem** [comment]
@k0kubun I'm glad to help with your excellent project :)

**Comment by k0kubun** [comment]
I fixed a little to make new features working and released at v0.4.1 :gem:

**Comment by bogem** [comment]
@k0kubun It's much better now :+1:

**Pull request merged**
