### PR TITLE
Add examples for all features

### PR DESCRIPTION
**Pull request by ecleel**
Hi,

I really like the Idea of starting presentation by writing markdown then move it afterward to keynote to design it. Kudos for all contributors.

I added examples in README file to all the features that missing documentation. touch #36

### CODE REVIEW

**Comment by k0kubun** [comment]
Nice documentation! Thanks 😸

**Comment by ecleel** [comment]
@k0kubun your most welcome 🌹

**Comment by jhonnymoreira** [comment]
This one closes issue #36, right?

**Comment by ecleel** [comment]
I don't know if I covered all the features but I write about what I know

**Comment by k0kubun** [comment]
Added a little in https://github.com/k0kubun/md2key/commit/d67483109710ac030a4e4c4c8418f3298503df2b and closed #36. Actually this PR covered almost all features. Thanks!

**Pull request merged**
