### PR TITLE
Use applescript

### PR DESCRIPTION
**Pull request by bogem**
Move AppleScript logic to separate AppleScript files:
* Reduce code (convenient to read Keynote class now)
* Improve performance (remove operations with creating new applescript files; remove code which create huge strings with AppleScript code)

### CODE REVIEW

**Comment by k0kubun** [comment]
It looks good. I want to merge this but it conflicts against master. Could you rebase it?
And please remove .DS_store.

**Comment by bogem** [comment]
@k0kubun no problem. Wait a minute, please

**Comment by bogem** [comment]
@k0kubun hm. Not a minute. You added more code. So wait an hour, please :)

**Comment by k0kubun** [comment]
:+1:

**Comment by bogem** [comment]
@k0kubun thanks

**Comment by bogem** [comment]
@k0kubun Done!

**Comment by k0kubun** [comment]
Closing in favor of https://github.com/k0kubun/md2key/pull/4

**Pull request closed without merging**
